repack-kernel: add more tests, fix setup command

diff --git a/tests/repack-kernel/task.yaml b/tests/repack-kernel/task.yaml
--- a/tests/repack-kernel/task.yaml
+++ b/tests/repack-kernel/task.yaml
@@ -18,9 +18,18 @@ execute: |
     kerneldir=/tmp/kernel-workdir
     repack-kernel extract "upstream-pc-kernel.snap" "$kerneldir"
 
+    # cull modules and firmware
+    repack-kernel cull-modules "$kerneldir"
+    repack-kernel cull-firmware "$kerneldir"
+
     # repack the initrd into the kernel.efi
     repack-kernel prepare "$kerneldir"
 
     # repack the kernel snap itself
     repack-kernel pack "$kerneldir" --filename=pc-kernel.snap
     rm -rf "$kerneldir"
+
+    if ![ -f "pc-kernel.snap" ]; then
+        echo "Repack failed, pc-kernel.snap was not created"
+        exit 1
+    fi
