Fixes for log-parser and changes for log analyzer

diff --git a/utils/log-analyzer b/utils/log-analyzer
--- a/utils/log-analyzer
+++ b/utils/log-analyzer
@@ -1,16 +1,11 @@
 #!/bin/bash
 
 show_help() {
-    echo "usage: log-analyzer get-failed-tasks <PARSED-LOG>"
-    echo "       log-analyzer get-successful-tasks <PARSED-LOG>"
-    echo "       log-analyzer get-aborted-tasks <PARSED-LOG>"
-    echo "       log-analyzer get-total-tasks <PARSED-LOG>"
-    echo "       log-analyzer get-failed <task|suite|project> <prepare|restore> <PARSED-LOG>"
-    echo "       log-analyzer list-failed <task|suite|project> <prepare|restore> <PARSED-LOG>"
-    echo "       log-analyzer list-failed-tasks <PARSED-LOG>"
-    echo "       log-analyzer list-executed-tasks <PARSED-LOG>"
-    echo "       log-analyzer list-successful-tasks <PARSED-LOG>"
+    echo "usage: log-analyzer list-failed-tasks <EXEC-PARAM> <PARSED-LOG>"
+    echo "       log-analyzer list-executed-tasks <EXEC-PARAM> <PARSED-LOG>"
+    echo "       log-analyzer list-successful-tasks <EXEC-PARAM> <PARSED-LOG>"
     echo "       log-analyzer list-aborted-tasks <EXEC-PARAM> <PARSED-LOG>"
+    echo "       log-analyzer list-all-tasks <EXEC-PARAM>"
     echo "       log-analyzer list-reexecute-tasks <EXEC-PARAM> <PARSED-LOG>"
     echo ""
     echo "Get general information about the current system"
@@ -19,16 +14,11 @@ show_help() {
     echo "  -h --help   show this help message."
     echo ""
     echo "COMMANDS:"
-    echo "  get-failed-tasks:        retrieves the number of failed tasks during preapre, execute or restore"
-    echo "  get-successful-tasks:    retrieves the number of successful tasks"
-    echo "  get-aborted-tasks:       retrieves the number of aborted tasks"
-    echo "  get-total-tasks          retrieves the number of successful, failed and aborted tasst"
-    echo "  get-failed               retrieves the number of failed tasks, suites or projects while preparing or restoring"
-    echo "  list-failed              list the failed tasks, suites or projects while preparing or restoring"
-    echo "  list-failed-tasks        list the tasks which failed during execute"
+    echo "  list-failed-tasks        list the tasks that failed during execute"
     echo "  list-executed-tasks      list the tasks that were executed"
     echo "  list-successful-tasks    list the successful tasks"
     echo "  list-aborted-tasks       list the aborted tasks (needs spread to be installed)"
+    echo "  list-all-tasks           list all the tasks"
     echo "  list-reexecute-tasks     list the tasks to re-execute to complete (includes aborted and failed tasks)"
     echo ""
     echo "PARSED-LOG: This is the output generated by the log-parser tool"
@@ -48,54 +38,7 @@ _check_log() {
     fi
 }
 
-get_successful_tasks() {
-    local log="$1"
-    _check_log "$log"
-
-    TESTS_SUCCESSFUL=$(jq -r '.[] | select( .type == "result") | ( select( .result_type == "Successful") | .number ) // 0 ' "$log" | awk '{s+=$1} END {print s}')
-    # shellcheck disable=SC2086
-    test $TESTS_SUCCESSFUL -gt 0
-    echo "$TESTS_SUCCESSFUL"
-}
-
-get_failed_tasks() {
-    local log="$1"
-    _check_log "$log"
-
-    TESTS_FAILED=$(jq -r '.[] | select( .type == "result") | ( select( .result_type == "Failed") | .number ) // 0 ' "$log" | awk '{s+=$1} END {print s}')
-    # shellcheck disable=SC2086
-    test $TESTS_FAILED -gt 0
-    echo "$TESTS_FAILED"
-}
-
-get_aborted_tasks() {
-    local log="$1"
-    _check_log "$log"
-
-    TESTS_ABORTED=$(jq -r '.[] | select( .type == "result") | ( select( .result_type == "Aborted") | .number ) // 0 ' "$log" | awk '{s+=$1} END {print s}')
-    # shellcheck disable=SC2086
-    test $TESTS_ABORTED -gt 0
-    echo "$TESTS_ABORTED"
-}
-
-get_total_tasks(){
-    local log="$1"
-    _check_log "$log"
-
-    TESTS_SUCCESSFUL=$(get_successful_tasks "$log")
-    TESTS_FAILED=$(get_failed_tasks "$log")
-    TESTS_ABORTED=$(get_aborted_tasks "$log")
-    echo "$((TESTS_SUCCESSFUL+TESTS_FAILED+TESTS_ABORTED))"
-}
-
-list_failed_tasks() {
-    local log="$1"
-    _check_log "$log"
-
-    jq -r '.[] | select( .type == "result") | select( .result_type == "Failed")  | select(.level == "tasks") | .detail.lines[]' "$log" | cut -d '-' -f2- | xargs
-}
-
-list_failed() {
+_list_failed() {
     local level="$1"
     local stage="$2"
     local log="$3"
@@ -118,31 +61,6 @@ list_failed() {
     _check_log "$log"
 
     jq -r ".[] | select( .type == \"result\") | select( .result_type == \"Failed\")  | select(.level == \"$level\") | select(.stage == \"$stage\")  | .detail.lines[]" "$log" | cut -d '-' -f2- | xargs
-}
-
-get_failed() {
-    local level="$1"
-    local stage="$2"
-    local log="$3"
-
-    if [ -z "$level" ]; then
-        echo "log.analyzer: the first parameter cannot be empty"
-        exit 1
-    elif [ ! "$level" = 'task' ] && [ ! "$level" = 'suite' ] && [ ! "$level" = 'project' ]; then
-        echo "log.analyzer: the first parameter has to be: task, suite or project"
-        exit 1
-    fi
-
-    if [ -z "$stage" ]; then
-        echo "log.analyzer: the second parameter cannot be empty"
-        exit 1
-    elif [ ! "$stage" = 'prepare' ] && [ ! "$stage" = 'restore' ]; then
-        echo "log.analyzer: the second parameter has to be: prepare or restore"
-        exit 1
-    fi
-    _check_log "$log"
-
-    jq -r ".[] | select( .type == \"result\") | ( select( .result_type == \"Failed\")  | ( select(.level == \"$level\") | ( select(.stage == \"$stage\")  | .number ))) // 0 " "$log" | awk '{s+=$1} END {print s}'
 }
 
 _merge_tasks_lists() {
@@ -192,6 +110,52 @@ _intersection_tasks_lists() {
     echo "$both_list"
 }
 
+list_all_tasks() {
+    local exec_exp="$1"
+    if ! command -v spread >/dev/null; then
+        echo "log.analyzer: spread tool is not installed, exiting..."
+        exit 1
+    fi
+
+    # shellcheck disable=SC2086
+    spread -list $exec_exp
+}
+
+_list_executed_and_failed_tasks() {
+    local exec_exp="$1"
+    local log="$2"
+
+    if ! command -v spread >/dev/null; then
+        echo "log.analyzer: spread tool is not installed, exiting..."
+        exit 1
+    fi
+    _check_log "$log"
+
+    local failed_tasks failed_tasks_restore failed_tasks_prepare exec_and_failed_tasks
+    failed_tasks="$(list_failed_tasks "$exec_exp" "$log")"
+    failed_tasks_prepare="$(_list_failed task prepare "$log")"
+    failed_tasks_restore="$(_list_failed task restore "$log")"
+
+    exec_and_failed_tasks="$(_merge_tasks_lists "$failed_tasks" "$failed_tasks_restore")"
+    _diff_tasks_lists "$exec_and_failed_tasks" "$failed_tasks_prepare"
+}
+
+list_failed_tasks() {
+    local exec_exp="$1"
+    local log="$2"
+
+    if [ -z "$exec_exp" ]; then
+        echo "log.analyzer: execution expression for spread cannot be empty"
+        exit 1
+    fi 
+    _check_log "$log"
+
+    local all_tasks failed_tasks
+    all_tasks="$(list_all_tasks "$exec_exp")"
+    failed_tasks="$(jq -r '.[] | select( .type == "result") | select( .result_type == "Failed")  | select(.level == "tasks") | .detail.lines[]' "$log" | cut -d '-' -f2- | xargs)"
+    _intersection_tasks_lists "$failed_tasks" "$all_tasks"
+}
+
 list_reexecute_tasks() {
     local exec_exp="$1"
     local log="$2"
@@ -204,11 +168,11 @@ list_reexecute_tasks() {
 
     local aborted_tasks exec_and_failed_tasks all_tasks reexec_tasks
     aborted_tasks="$(list_aborted_tasks "$exec_exp" "$log")"
-    all_tasks="$(_list_all_tasks "$exec_exp")"
-    exec_and_failed_tasks="$(_list_executed_and_failed_tasks "$log")"
+    all_tasks="$(list_all_tasks "$exec_exp")"
+    exec_and_failed_tasks="$(_list_executed_and_failed_tasks "$exec_exp" "$log")"
 
     # Remove the tasks which are not in the filter from the executed and failed
-    exec_and_failed_tasks="$(_intersection_tasks_lists "$exec_and_failed_tasks" "$all_tasks" "$log")"
+    exec_and_failed_tasks="$(_intersection_tasks_lists "$exec_and_failed_tasks" "$all_tasks")"
     reexec_tasks="$(_merge_tasks_lists "$aborted_tasks" "$exec_and_failed_tasks")"
 
     # In case all the tests are failed or aborted, then the execution expression is used to reexecute
@@ -225,13 +189,21 @@ list_reexecute_tasks() {
 }
 
 list_successful_tasks() {
-    local log="$1"
+    local exec_exp="$1"
+    local log="$2"
+
+    if [ -z "$exec_exp" ]; then
+        echo "log.analyzer: execution expression for spread cannot be empty"
+        exit 1
+    fi
     _check_log "$log"
 
-    local executed_tasks failed_tasks_restore failed_tasks
-    executed_tasks="$(list_executed_tasks "$log")"
-    failed_tasks="$(list_failed_tasks "$log")"
-    failed_tasks_restore="$(list_failed task restore "$log")"
+    local all_tasks executed_tasks failed_tasks_restore failed_tasks
+    all_tasks="$(list_all_tasks "$exec_exp")"
+    executed_tasks="$(list_executed_tasks "$exec_exp" "$log")"
+    executed_tasks="$(_intersection_tasks_lists "$executed_tasks" "$all_tasks")"
+    failed_tasks="$(list_failed_tasks "$exec_exp" "$log")"
+    failed_tasks_restore="$(_list_failed task restore "$log")"
 
     if [ -n "$failed_tasks_restore" ]; then
         failed_tasks="$(_merge_tasks_lists "$failed_tasks" "$failed_tasks_restore")"
@@ -245,33 +217,19 @@ list_successful_tasks() {
 }
 
 list_executed_tasks() {
-    local log="$1"
-    _check_log "$log"
-    jq -r '.[] | select( .type == "action") | select( .verb == "Executing") | .task' "$log"
-}
-
-_list_all_tasks() {
     local exec_exp="$1"
-    if ! command -v spread >/dev/null; then
-        echo "log.analyzer: spread tool is not installed, exiting..."
+    local log="$2"
+
+    if [ -z "$exec_exp" ]; then
+        echo "log.analyzer: execution expression for spread cannot be empty"
         exit 1
-    fi
-
-    # shellcheck disable=SC2086
-    spread -list $exec_exp
-}
-
-_list_executed_and_failed_tasks() {
-    local log="$1"
+    fi 
     _check_log "$log"
 
-    local failed_tasks failed_tasks_restore failed_tasks_prepare exec_and_failed_tasks
-    failed_tasks="$(list_failed_tasks "$log")"
-    failed_tasks_prepare="$(list_failed task prepare "$log")"
-    failed_tasks_restore="$(list_failed task restore "$log")"
-
-    exec_and_failed_tasks="$(_merge_tasks_lists "$failed_tasks" "$failed_tasks_restore")"
-    _diff_tasks_lists "$exec_and_failed_tasks" "$failed_tasks_prepare"
+    local all_tasks executed_tasks
+    all_tasks="$(list_all_tasks "$exec_exp")"
+    executed_tasks="$(jq -r '.[] | select( .type == "action") | select( .verb == "Executing") | .task' "$log")"
+    _intersection_tasks_lists "$executed_tasks" "$all_tasks"
 }
 
 list_aborted_tasks() {
@@ -285,11 +243,11 @@ list_aborted_tasks() {
     _check_log "$log"
 
     local all_tasks executed_tasks failed_tasks_prepare failed_tasks_restore failed_tasks
-    all_tasks="$(_list_all_tasks "$exec_exp")"
-    executed_tasks="$(list_executed_tasks "$log")"
-    failed_tasks="$(list_failed_tasks "$log")"
-    failed_tasks_prepare="$(list_failed task prepare "$log")"
-    failed_tasks_restore="$(list_failed task restore "$log")"
+    all_tasks="$(list_all_tasks "$exec_exp")"
+    executed_tasks="$(list_executed_tasks "$exec_exp" "$log")"
+    failed_tasks="$(list_failed_tasks "$exec_exp" "$log")"
+    failed_tasks_prepare="$(_list_failed task prepare "$log")"
+    failed_tasks_restore="$(_list_failed task restore "$log")"
 
     # In case no tasks for the expression, the aborted list is empty
     if [ -z "$all_tasks" ]; then
@@ -298,7 +256,7 @@ list_aborted_tasks() {
 
     # In case no tasks are successfully executed, all the tasks - the failed ones are the aborted
     if [ -z "$executed_tasks" ]; then
-        exec_and_failed_tasks="$(_list_executed_and_failed_tasks "$log")"
+        exec_and_failed_tasks="$(_list_executed_and_failed_tasks "$exec_exp" "$log")"
         _diff_tasks_lists "$all_tasks" "$exec_and_failed_tasks"
         return
     fi
@@ -340,3 +298,4 @@ main() {
 
 main "$@"
 
+    
