review feedback

diff --git a/tools/repack-kernel b/tools/repack-kernel
--- a/tools/repack-kernel
+++ b/tools/repack-kernel
@@ -1,11 +1,7 @@
 #!/bin/bash
-
-# Author: Maciej Borzecki
-# Modified by Ian Johnson <ian.johnson@canonical.com>
-
 set -e
 
-if [[ -n "$D" ]]; then
+if [ -n "$D" ]; then
     set -x
 fi
 
@@ -15,17 +11,17 @@ show_help() {
     echo "handle extraction of the kernel snap to a workspace directory, and later"
     echo "repacking it back to a snap."
     echo ""
-    echo "   setup                          - setup system dependencies"
-    echo "   extract <snap-file> <target>   - extract under <target> workspace tree"
-    echo "   prepare <target>               - prepare initramfs & kernel for repacking"
-    echo "   pack <target>                  - pack the kernel"
-    echo "   cull-firmware <target>         - remove unnecessary firmware"
-    echo "   cull-modules <target>          - remove unnecessary modules"
+    echo "   repack-kernel setup                        - setup system dependencies"
+    echo "   repack-kernel extract <snap-file> <target> - extract under <target> workspace tree"
+    echo "   repack-kernel prepare <target>             - prepare initramfs & kernel for repacking"
+    echo "   repack-kernel pack <target>                - pack the kernel"
+    echo "   repack-kernel cull-firmware <target>       - remove unnecessary firmware"
+    echo "   repack-kernel cull-modules <target>        - remove unnecessary modules"
     echo ""
 }
 
 setup_deps() {
-    if [[ "$UID" != "0" ]]; then
+    if [ "$UID" != "0" ]; then
         echo "run as root (only this command)"
         exit 1
     fi
@@ -45,12 +41,12 @@ get_kver() {
     )
 }
 
-extract_kernel() {
+extract() {
     local snap_file="$1"
     local target="$2"
 
-    if [[ -z "$target" ]] || [[ -z "$snap_file" ]]; then
-        echo "usage: prepare <target-dir> <kernel-snap>"
+    if [ -z "$target" ] || [ -z "$snap_file" ]; then
+        echo "repack-kernel: invalid argument for prepare"
         exit 1
     fi
 
@@ -101,8 +97,8 @@ extract_kernel() {
 prepare_kernel() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: repack <extract-tree>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for repack"
         exit 1
     fi
 
@@ -146,7 +142,7 @@ prepare_kernel() {
 cull_firmware() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
+    if [ -z "$target" ]; then
         echo "usage: cull-firmware <extract-tree>"
         exit 1
     fi
@@ -161,12 +157,12 @@ cull_firmware() {
 cull_modules() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: cull-modules <extract-tree>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for cull-modules"
         exit 1
     fi
 
-    target=$(realpath "$target")
+    target="$(realpath $target)"
     kver="$(get_kver "$target/kernel")"
 
     (
@@ -194,42 +190,42 @@ cull_modules() {
 pack() {
     local target="$1"
 
-    if [[ -z "$target" ]]; then
-        echo "usage: pack <extract-tree> <opts to snap pack>"
+    if [ -z "$target" ]; then
+        echo "repack-kernel: missing target for pack"
         exit 1
     fi
     snap pack "${@:2}" "$target/kernel" 
 }
 
 main() {
-    opt="$1"
-    shift || true
+    if [ $# -eq 0 ]; then
+        show_help
+        exit 0
+    fi
 
-    if [[ -z "$opt" ]] || [[ "$opt" == "--help" ]]; then
+    local subcommand="$1"
+    local action=
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -h|--help)
+                show_help
+                exit 0
+                ;;
+            *)
+                action=$(echo "$subcommand" | tr '-' '_')
+                shift
+                break
+                ;;
+        esac
+    done
+
+    if [ -z "$(declare -f "$action")" ]; then
+        echo "log.analyzer: no such command: $subcommand" >&2
         show_help
         exit 1
     fi
 
-    case "$opt" in
-        setup)
-            setup_deps
-            ;;
-        extract)
-            extract_kernel "$@"
-            ;;
-        prepare)
-            prepare_kernel "$@"
-            ;;
-        cull-modules)
-            cull_modules "$@"
-            ;;
-        cull-firmware)
-            cull_firmware "$@"
-            ;;
-        pack)
-            pack "$@"
-            ;;
-    esac
+    "$action" "$@"
 }
 
 main "$@"
